packages:
  # All packages in direct subdirs of packages/
  - 'packages/*'
  # All packages in subdirs of components/
  - 'packages/components/*'
  # Exclude files from being included in the workspace
  - '!**/test/**'
  - '!**/tests/**'
  - '!**/dist/**' 